---

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: latest

- name: Copy dnsmasq configuration
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "u=rw,go=r"
