---
- name: Install soft
  tags: install-soft
  package:
    name: "{{packages|join(',')}}"
    state: latest
    update_cache: yes

- name: Install debsecan
  tags: install-soft
  package:
    name: debsecan
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
