---
# create and attach a new aws volume using dynamic inventory
- name: create and attach a new aws volume using dynamic inventory
  hosts: "{{ passed_in_hosts }}"
  gather_facts: False
  tasks:
    - name: create/attach new volume {{ device_name }}
      connection: local
      ec2_vol:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        volume_size: "{{ volume_size }}"
        volume_type: "{{ volume_type }}"
        device_name: "{{ device_name  }}"
        instance:  "{{ instance_id }}" # variable from dynamic inventory
        delete_on_termination: true
        region: "{{ placement.region }}" # variable from dynamic inventory
        zone: "{{ placement.availability_zone }}" # variable from dynamic inventory
      register: new_volume

    - name: tag new volume {{ device_name }}
      connection: local
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource: "{{ new_volume.volume_id }}"
        region: "{{ placement.region  }}" # variable from dynamic inventory
        state: present
        tags:
          Name: "{{ tags.Name }}" # variable from dynamic inventory
      register: tag_volume

# ansible-playbook -e "passed_in_hosts=tag_Name_cygnusx1 aws_access_key=<REDACTED> aws_secret_key=<REDACTED>  volume_size=8 volume_type=gp2 device_name=/dev/xvdb " create_and_attach_aws_volume.yml
# ansible-playbook -e "passed_in_hosts=tag_Project_Orpheus aws_access_key=<REDACTED> aws_secret_key=<REDACTED>  volume_size=8 volume_type=gp2 device_name=/dev/xvdb " create_and_attach_aws_volume.yml
