---
# variables from dynamic inventory
- name: variables from dynamic inventory
  hosts: "{{ passed_in_hosts }}"
  remote_user: ec2-user # user used to connect to AWS servers.
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: Debug my ec2 instances
    debug:
      msg: "hostname: {{ ansible_hostname }}"

  - name: display variables from dynamic inventory
    vars:
      myVar: |
        Name: {{ tags.Name }}
        Instance Id: {{ instance_id }}
        Region: {{ placement.region }}
        Zone: {{ placement.availability_zone }}
        Instance Type: {{  instance_type }}
        Public Ip: {{ public_ip_address }}
        Private Ip: {{ private_ip_address }}
        Image Id: {{ image_id }}
        VPC Id: {{ vpc_id}}
        Security Groups: {{ security_groups }}
        Subnet: {{ subnet_id }}
        Launch: {{ launch_time }}
        Architecture: {{ architecture }}
        Hypervisor: {{ hypervisor }}
        Virtualization: {{ virtualization_type }}
        Key Name: {{ key_name }}
        Root Device: {{ root_device_name }}
        Tags: {{ tags }}
    debug:
      msg: "{{ myVar.split('\n') }}"

# ansible-playbook -e "passed_in_hosts=tag_Environment_ssudemo" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=tag_Project_Orpheus" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=tag_Applications_Oracle" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=aws_region_us_east_1" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=aws_instance_type_t2_micro" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=arch_x86_64" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=aws_image_ami_0b898040803850657" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=security_groups_sg_<REDACTED>" display_dynamic_variables.yml
# ansible-playbook -e "passed_in_hosts=tag_SubType_Steller_Mass" display_dynamic_variables.yml
